include Makefile.rules

PACKAGES = unix

OBJ = rtypes.cmo syntax.cmo options.cmo parser.cmo lexer.cmo rename.cmo \
	generate.cmo cgen.cmo main.cmo

XOBJ = $(OBJ:.cmo=.cmx)

OCAMLC_OPTIONS = -I ..
OCAMLOPT_OPTIONS = -I ..

all: ocamlrpcgen

ocamlrpcgen: $(OBJ)
	$(OCAMLC) -custom -o ocamlrpcgen $(OBJ) -linkpkg

include depend

